apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-tcp-log
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config:
  host: logstash-logstash.elk.svc.cluster.local
  port: 1514
  custom_fields_by_lua:
    request.batata: "return kong.request.get_header('h1')"
plugin: tcp-log