_format_version: "1.1"
services:
  - name: Loan
    protocol: https
    host: virtserver.swaggerhub.com
    port: 443
    path: /BIAN-3/Loan/10.0.0
    plugins: []
    routes:
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-Initiate
        methods:
          - POST
        paths:
          - /Loan/Initiate$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-Update
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Update$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-Retrieve
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveInterest
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Interest/(?<interestId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-ExecuteServiceFees
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/ServiceFees/(?<servicefeesId>[^\/]+)/Execute$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveServiceFees
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/ServiceFees/(?<servicefeesId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveDisbursement
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Disbursement/(?<disbursementId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RequestMaintenance
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Maintenance/(?<maintenanceId>[^\/]+)/Request$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveMaintenance
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Maintenance/(?<maintenanceId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-UpdateWithdrawal
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Withdrawal/(?<withdrawalId>[^\/]+)/Update$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-ExecuteWithdrawal
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Withdrawal/(?<withdrawalId>[^\/]+)/Execute$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RequestWithdrawal
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Withdrawal/(?<withdrawalId>[^\/]+)/Request$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveWithdrawal
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Withdrawal/(?<withdrawalId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-UpdateRepayment
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Repayment/(?<repaymentId>[^\/]+)/Update$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-ExecuteRepayment
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Repayment/(?<repaymentId>[^\/]+)/Execute$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RequestRepayment
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Repayment/(?<repaymentId>[^\/]+)/Request$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveRepayment
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Repayment/(?<repaymentId>[^\/]+)/Retrieve$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-InitiateRestructuring
        methods:
          - POST
        paths:
          - /Loan/(?<loanId>[^\/]+)/Restructuring/Initiate$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-UpdateRestructuring
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Restructuring/(?<restructuringId>[^\/]+)/Update$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RequestRestructuring
        methods:
          - PUT
        paths:
          - /Loan/(?<loanId>[^\/]+)/Restructuring/(?<restructuringId>[^\/]+)/Request$
        strip_path: false
      - tags:
          - OAS3_import
          - OAS3file_BIAN-loan.yaml
        name: Loan-RetrieveRestructuring
        methods:
          - GET
        paths:
          - /Loan/(?<loanId>[^\/]+)/Restructuring/(?<restructuringId>[^\/]+)/Retrieve$
        strip_path: false
    tags:
      - OAS3_import
      - OAS3file_BIAN-loan.yaml
