persistence:
  enabled: true  # enable persistence using Persistent Volumes
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-kong-server
        access: proxy
        isDefault: true
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    kong-dash:
      gnetId: 7424  # Install the following Grafana dashboard in the
      revision: 7   # instance: https://grafana.com/dashboards/7424
      datasource: Prometheus
ingress:
  enabled: true
  ingressClassName: kong
  hosts:
    - "grafana.local"
grafana.ini:
  server:
    domain: grafana.local