podAnnotations:
  prometheus.io/scrape: "true" # Ask Prometheus to scrape the
  prometheus.io/port: "8100"   # Kong pods for metrics
admin:
  tls:
    parameters: []

env: 
  plugins: bundled, oidc

image:
  repository: giovanibrioni/kong-oidc
  tag: "2.8"
  # Kong Enterprise
  # repository: kong/kong-gateway
  # tag: "2.8"

  pullPolicy: IfNotPresent

# Specify Kong proxy service configuration
proxy:
  # Enable creating a Kubernetes service for the proxy
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels:
    enable-metrics: "true"

  http:
    # Enable plaintext HTTP listen for the proxy
    enabled: true
    hostPort: 80
    containerPort: 8000
    parameters: []

  tls:
    # Enable HTTPS listen for the proxy
    enabled: true
    hostPort: 443
    containerPort: 8443
    parameters:
    - http2
