# Basic configuration for Kong without the ingress controller, using the Postgres subchart
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001

image:
  repository: kong/kong-gateway
  tag: "2.8"

env:
  prefix: /kong_prefix/
  database: postgres
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  cluster_telemetry_listen: 0.0.0.0:8006

admin:
  enabled: true
  http:
    enabled: true
    servicePort: 8001
    containerPort: 8001

cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005

proxy:
  enabled: false

secretVolumes:
- kong-cluster-cert

postgresql:
  enabled: true
  auth:
    username: kong
    database: kong

ingressController:
  enabled: false

enterprise:
  enabled: true
  vitals:
    enabled: false
  rbac:
    admin_api_auth: basic-auth
    enabled: true
    session_conf_secret: kong-session-config

manager:
  # Enable creating a Kubernetes service for Kong Manager
  enabled: true

portal:
  enabled: false

portalapi:
  enabled: false

clustertelemetry:
  enabled: true