# Basic configuration for Kong without the ingress controller, using the Postgres subchart
# This installation does not create an Ingress or LoadBalancer Service for
# the Admin API. It requires port-forwards to access without further
# configuration to add them, e.g.:
# kubectl port-forward deploy/your-deployment-kong 8001:8001

image:
  repository: giovanibrioni/kong-oidc
  tag: "latest"

env:
  prefix: /kong_prefix/
  database: postgres
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  plugins: bundled, oidc, http-log-multi-body, jwt-keycloak

admin:
  enabled: true
  http:
    enabled: true
    hostPort: 8001
    containerPort: 8001

cluster:
  enabled: true
  tls:
    enabled: true
    hostPort: 8005
    containerPort: 8005

proxy:
  enabled: false

secretVolumes:
- kong-cluster-cert

postgresql:
  enabled: true
  auth:
    username: kong
    database: kong

ingressController:
  enabled: false